

spring:
  profiles:
    active: dev
  # kafka:
  #   bootstrap-servers: glider.srvs.cloudkafka.com:9094
  #   properties:
  #     security.protocol: SASL_SSL
  #     sasl.mechanism: SCRAM-SHA-256
  #     sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="eybaugdf" password="hb2umr-KlHM0JSQG68vvhubTJtxFA6Gc";
  #   consumer:
  #     group-id: eybaugdf-ProductService
  tomcat:
    threads:
      max: 2
  application:
    name: PRODUCT-SERVICE
  # DB CONFIG
  data:
    jpa:
      repositories:
        enabled: true
   
  jpa:
    database: MYSQL
  # Hibernate ddl auto (create, create-drop, validate, update) 
    hibernate:
      ddlAuto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8079/eureka}
  instance:
    preferIpAddress: true
server:
  servlet:
    context-path: /product
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiredInDays: 1
