

spring:
  
  # DB CONFIG
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
        platform: mariadb
        # driverClassName: org.mariadb.jdbc.Driver
        driver-class-name: org.mariadb.jdbc.Driver
        # Fixed in v1.3.3. Doesn't work with mariadb-connector-j v1.3.2 (CONJ-227)
        url: jdbc:mariadb:failover://localhost:3306/ms_product?autoReconnect=true
        # If some of the hosts is down, app won't launch. v1.3.3
        #url: jdbc:mariadb:failover://192.168.33.11:3306,192.168.33.12:3306,192.168.33.13:3306/test?autoReconnect=true
        # Works with mariadb-connector-j v1.3.2
        #url: jdbc:mysql:failover://192.168.33.11:3306/test
        username: root
        password: tekanenter

        timeBetweenEvictionRunsMillis: 1000
        testWhileIdle: true
        validationQuery: SELECT 1
 