
spring: 
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  tomcat:
    threads:
      max: 2
  application:
    name: AUTH-SERVICE
  # DB CONFIG
  data:
    jpa:
      repositories:
        enabled: true
   
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_URI:http://localhost:8079/eureka}
#   instance:
#     preferIpAddress: true
server:
  servlet:
    context-path: /auth
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: true
    whitelabel:
      enabled: false
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiredInDays: 7